config/routes.rb
GoodLivingNutrition::Application.routes.draw do

  

  resources :entries

  resources :diaries, except: [:destroy, :new, :create] do
    resources :entries
  end

  resources :mealplans, except: [:destroy, :new, :create] do
    resources :meals
  end

  devise_for :users

  get "welcome/index"
  match '/users/:id' => 'mealplans#delete_user'

  root :to => 'welcome#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :diary
  attr_accessible :comment, :day
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    #@entries = Entry.all
    @diary = Diary.find(params[:diary_id])
    @entries = @diary.entries

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    #@entry = Entry.find(params[:id])
    @diary = Diary.find(params[:diary_id])
    @entry = @diary.entires.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new
    @diary = Diary.find(params[:diary_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    #@entry = Entry.find(params[:id])
    @diary = Diary.find(params[:diary_id])
    @entry = @diary.entries.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    #@entry = Entry.new(params[:entry])
    @diary = Diary.find(params[:diary_id])
    @entry = @diary.entries.build(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to diary_path(@diary), notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    #@entry = Entry.find(params[:id])
    @diary = Diary.find(params[:diary_id])
    @entry = @diary.entries.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to diary_path(@diary), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    #@entry = Entry.find(params[:id])
    @diary = Diary.find(params[:diary_id])
    @entry = @diary.entires.find(params[:id])

    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for [@diary, @entry] do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%#= f.label :diary %><br />
    <%#= f.text_field :diary %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                :back, :class => 'btn' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Comment</th>
    <th>Diary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.day %></td>
    <td><%= entry.comment %></td>
    <td><%= entry.diary %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @entry.day %>
</p>

<p>
  <b>Comment:</b>
  <%= @entry.comment %>
</p>

<p>
  <b>Diary:</b>
  <%= @entry.diary %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>