config/routes.rb
GoodLivingNutrition::Application.routes.draw do

  

  resources :entries

  resources :diaries, except: [:destroy, :new, :create] do
    resources :entries
  end

  resources :mealplans, except: [:destroy, :new, :create] do
    resources :meals
  end

  devise_for :users

  get "welcome/index"
  match '/users/:id' => 'mealplans#delete_user'

  root :to => 'welcome#index'

end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :user_id
  has_many :entries
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diaries }
    end
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
    #@diary = Diary.find(params[:id])
    if current_user && current_user.admin
       @diary = Diary.find(params[:id]) 
    elsif  current_user.id == params[:id].to_i
      @diary = Diary.find(params[:id])
    else
      redirect_to diary_path(current_user.id), alert: "You can't do that!!!"
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diary }
    end
  end

  # GET /diaries/new
  # GET /diaries/new.json
  def new
    @diary = Diary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diary }
    end
  end

  # GET /diaries/1/edit
  def edit
    @diary = Diary.find(params[:id])
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(params[:diary])

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render json: @diary, status: :created, location: @diary }
      else
        format.html { render action: "new" }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diaries/1
  # PUT /diaries/1.json
  def update
    @diary = Diary.find(params[:id])

    respond_to do |format|
      if @diary.update_attributes(params[:diary])
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to diaries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_form.html.erb
<%= form_for(@diary) do |f| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing diary</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<h1>Listing diaries</h1>

<table class="table table-striped">
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diaries.each do |diary| %>
<% unless diary.user.admin %>
  <tr>
    <td><%= diary.user.email %></td>
    <td><%= link_to 'Show', diary %></td>
    <td><%#= link_to 'Edit', edit_diary_path(diary) %></td>
    <td><%#= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

app/views/diaries/new.html.erb
<h1>New diary</h1>

<%= render 'form' %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Food diary for: <%= @diary.user.email %></h2>


<% if current_user.try(:admin?) %>
<div class="form-actions">
  <%= link_to 'Edit Title', edit_diary_path(@diary), :class => 'btn btn-success'  %>
  <%= link_to 'Return to list of diaries', diaries_path, :class => 'btn btn-success'  %>
</div>
<% end %>

<% if @diary.entries.length!=0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%#= model_class.human_attribute_name(:id) %></th>
      <th><%#= model_class.human_attribute_name(:day) %></th>
      <th><%#= model_class.human_attribute_name(:comment) %></th>
      <th><%#= model_class.human_attribute_name(:diary_id) %></th>
      <th><%#=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diary.entries.each do |entry| %>
      <tr >
        <td><%#= link_to meal.id, mealplan_meal_path(mealplan, meal) %></td>
        <td style="background-color: lightgrey"><%= entry.day %></td>
        <td style="background-color: lightgrey"><textarea style="width: 500px; height: 100px;"><%= entry.comment %></textarea></td>
        <td><%#= entry.diary_id %></td>
        <td><%#=l meal.created_at %></td>
        <td style="float:right; background-color: white">
          <%= link_to 'edit comment', edit_diary_entry_path(@diary, entry), :class => 'btn btn-primary'  %>
          <%= link_to 'delete comment', diary_entry_path(@diary, entry), :method => :delete, :class => 'btn btn-primary' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h2>Your diary has not been set up yet, please try again soon.</h2>
<% end %>



<%= link_to 'Add New Comment', new_diary_entry_path(@diary), :class => 'btn btn-primary'  %>


<%#= link_to 'Edit', edit_diary_path(@diary) %> |
<%#= link_to 'Back', mealplan_path(:id) %>