config/routes.rb
GoodLivingNutrition::Application.routes.draw do

  

  resources :entries

  resources :diaries, except: [:destroy, :new, :create] do
    resources :entries
  end

  resources :mealplans, except: [:destroy, :new, :create] do
    resources :meals
  end

  devise_for :users

  get "welcome/index"
  match '/users/:id' => 'mealplans#delete_user'

  root :to => 'welcome#index'

end

app/models/mealplan.rb
class Mealplan < ActiveRecord::Base
  belongs_to :user
  attr_accessible :end, :start, :user_id, :title
  has_many :meals

end

app/controllers/mealplans_controller.rb
class MealplansController < ApplicationController
  require 'Calendar'
  # GET /mealplans
  # GET /mealplans.json
  def index
    @mealplans = Mealplan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mealplans }
    end
  end

  # GET /mealplans/1
  # GET /mealplans/1.json
  def show
    if current_user && current_user.admin
      @mealplan = Mealplan.find(params[:id]) #.find(params[:id])
      @mymeals = @mealplan.meals.order(:day)
    elsif  current_user.id == params[:id].to_i
      @mealplan = Mealplan.find(params[:id])
      @mymeals = @mealplan.meals.order(:day)
    else
      redirect_to mealplan_path(current_user.id), alert: "You can't do that!!!"
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mealplan }
    end
  end

  # GET /mealplans/new
  # GET /mealplans/new.json
  def new
    @mealplan = Mealplan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mealplan }
    end
  end

  # GET /mealplans/1/edit
  def edit
     if current_user && current_user.admin
       @mealplan = Mealplan.find(params[:id]) #.find(params[:id])
    else
      redirect_to mealplan_path(current_user.id), alert: "You can't do that!!!"
      return
    end
  end

  # POST /mealplans
  # POST /mealplans.json
  def create
    @mealplan = Mealplan.new(params[:mealplan])

    respond_to do |format|
      if @mealplan.save
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully created.' }
        format.json { render json: @mealplan, status: :created, location: @mealplan }
      else
        format.html { render action: "new" }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mealplans/1
  # PUT /mealplans/1.json
  def update
    @mealplan = Mealplan.find(params[:id])

    respond_to do |format|
      if @mealplan.update_attributes(params[:mealplan])
        format.html { redirect_to @mealplan, notice: 'Mealplan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mealplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mealplans/1
  # DELETE /mealplans/1.json
  def destroy
    @user = User.find(params[:user_id])
    @mealplan = Mealplan.find(params[:id])
    #@mealplan.destroy
    user.destroy

    respond_to do |format|
      format.html { redirect_to mealplans_url }
      format.json { head :no_content }
    end
  end

  def delete_user
    @user = User.find(params[:id])
    @mealplan = Mealplan.find_by_user_id(params[:id])
    @diary = Diary.find_by_user_id(params[:id])
    @mealplan.destroy
    @user.destroy
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to mealplans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mealplans_helper.rb
module MealplansHelper
end

app/views/mealplans/_form.html.erb
<%= form_for @mealplan, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :start, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :start, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :end, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                mealplans_path, :class => 'btn' %>
  </div>

<% end %>

app/views/mealplans/edit.html.erb
<%- model_class = Mealplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mealplans/index.html.erb
<%- model_class = Mealplan -%>
<div class="page-header">
  <h1><%#=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h1>List of all users and their meal plans</h2>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:user_email) %></th>
      <th><%= model_class.human_attribute_name(:start) %></th>
      <th><%= model_class.human_attribute_name(:end) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mealplans.each do |mealplan| %>
      <tr>
        <% unless mealplan.user.admin %>
        <td><%= link_to mealplan.user.email, mealplan_path(mealplan) %></td>
        <td><%= mealplan.start %></td>
        <td><%= mealplan.end %></td>
        <td>
          <%= link_to t('view meal plan', :default => t("helpers.links.show")),
                      mealplan_path(mealplan), :class => 'btn btn-success' %>
          <a href = "users/<%= mealplan.id %>" class='btn btn-mini btn-danger' onclick="return confirm('Are you sure? This will delete the user and all their meals from the system!');">Delete User From System</a>
          <%#= link_to 'delete meal', mealplan_meal_path(@mealplan, meal), :method => :delete, :class => 'btn btn-primary' %>
          <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mealplan_path(mealplan),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_mealplan_path,
            :class => 'btn btn-primary' %>

app/views/mealplans/new.html.erb
<%- model_class = Mealplan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mealplans/show.html.erb
<%- model_class = Mealplan -%>
<div class="page-header">
  <h2>Diet Program for: <%= @mealplan.user.email %></h2>
</div>
<%#= @mealplan.inspect %>
<%#= debug @mymeals %>
<dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:start) %>:</strong></dt>
  <dd><%= @mealplan.start %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end) %>:</strong></dt>
  <dd><%= @mealplan.end %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @mealplan.title %></dd>
</dl>

<!-- data is displayed in a different format for admin and noraml users -->
<% if current_user.try(:admin?) %>
<!-- only admin can edit dates for a diet progam -->
  <div class="form-actions">
    <%= link_to 'Edit Dates', edit_mealplan_path(@mealplan), :class => 'btn btn-success' %>
    <%= link_to 'Return to list of meal plans', mealplans_path, :class => 'btn btn-success'  %>
  </div>
<% end %>

  <!-- test comment -->
  <!-- if no meals exist yet in the diet program, they can't be displayed -->
  <% if @mealplan.meals.length!=0 %>

      <!-- loop through all the meals in the diet program -->
      <div class="mycalendar">
        <% @mymeals.each do |meal| %>
        <table class="mytable">

          <!-- header is the date -->
            <thead>
              <tr><th colspan="2"><%= meal.day %></th></tr>
            </thead>
            <tbody>
              <tr><td>Breakfast: </td><td><a href="/recipes/<%= meal.breakfast %>" target="_blank"><%= meal.breakfast %></a></td></tr>
              <tr><td>Lunch: </td><td><a href="/recipes/<%= meal.lunch %>" target="_blank"><%= meal.lunch %></a></td></tr>
              <tr><td>Dinner: </td><td><a href="/recipes/<%= meal.dinner %>" target="_blank"><%= meal.dinner %></a></td></tr>
              <!-- only allow the admin to edit or delete a meal -->
              <% if current_user.try(:admin?) %>
                <tr>
                  <td><%= link_to 'edit meal', edit_mealplan_meal_path(@mealplan, meal), :class => 'btn btn-primary'  %></td>
                  <td><%= link_to 'Delete', mealplan_meal_path(@mealplan, meal), method: :delete, :class => 'btn btn-danger'  %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
          <% end %>
      </div>
  <%# end %>

  <!-- else no diet program has been set up for this user yet -->
  <% else %>
      <!-- show different message for regular user and admin -->
      <% if current_user.try(:admin?) %>
        <h3> No meals have been added yet to this diet program</h3>
      <% else %>
        <h3>Your diet program has not been set up yet, please try again soon.</h3>
      <% end %>
  <% end %>

<!-- only allow the admin to add or edit a meal -->
<% if current_user.try(:admin?) %>
  <div class="form-actions" style="clear:both;">
    <%= link_to 'add meal', new_mealplan_meal_path(@mealplan), :class => 'btn btn-primary'  %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                mealplans_path, :class => 'btn'  %>
  </div>
<% end %>

</div>