config/routes.rb
GoodLivingNutrition::Application.routes.draw do

  

  resources :entries

  resources :diaries, except: [:destroy, :new, :create] do
    resources :entries
  end

  resources :mealplans, except: [:destroy, :new, :create] do
    resources :meals
  end

  devise_for :users

  get "welcome/index"
  match '/users/:id' => 'mealplans#delete_user'

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GoodLivingNutrition" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="mycontainer">
    <div class="navbar navbar-fluid-top">
      <img src="/logo.jpg" alt="Site Header"  /><br />
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container-fluid nav-collapse">
            <!--<img src="/assets/banner1.jpg" alt="Site Header"  /><br />-->
            <ul class="mynav">
              <br/>
              <% if current_user  %>
                <% if !current_user.admin %>
                  <li><%= link_to "View Diet Program", mealplan_path(current_user.id)  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if current_user.admin%>
                  <li><%= link_to "List All Programs", mealplans_path  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if !current_user.admin %>
                  <li><%= link_to "View Diary", diary_path(current_user.id)  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if current_user.admin%>
                  <li><%= link_to "List All Diaries", diaries_path  %></li>
                <% end %>
              <% end %>
              <% if current_user%>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    

    <div class="container-fluid">
      <div class="row-fluid">
        
        <div class="span3">
          <div class="well sidebar-nav">
            <div class="myimages">
              <img src="/assets/nav-banner.jpg" alt="Images of fruit" />
              <!--
              <img src="/assets/fruit2.jpg" alt="Site Header" />

              <img src="/assets/fruit1.jpg" alt="Site Header" />
             
              <img src="/assets/image1.jpg" alt="Site Header" />
              -->
            </div>
            <!--
            <ul class="nav nav-list">
              <% if current_user  %>
                <% if !current_user.admin %>
                  <li><%= link_to "View Diet Program", mealplan_path(current_user.id)  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if current_user.admin%>
                  <li><%= link_to "List All Programs", mealplans_path  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if !current_user.admin %>
                  <li><%= link_to "View Diary", diary_path(current_user.id)  %></li>
                <% end %>
              <% end %>
              <% if current_user  %>
                <% if current_user.admin%>
                  <li><%= link_to "List All Diaries", diaries_path  %></li>
                <% end %>
              <% end %>
              <% if current_user%>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path  %></li>
              <% end %>
            </ul>
          -->
          </div>
        </div>
        
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->
    </div>
  </body>
</html>